kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
  name: nginx-app-http
spec:
  hosts:
    - myhost.com
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-app
    service: nginx-app
    port: 80
  replicas:
    min: 0
    max: 10
